apiVersion: v1
kind: Namespace
metadata:
  name: knet-stress
---
apiVersion: v1
kind: Service
metadata:
  name: knet-stress
  namespace: knet-stress
spec:
  selector:
    app: knet-stress
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knet-stress
  namespace: knet-stress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: knet-stress
  name: knet-stress
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: knet-stress
  namespace: knet-stress
subjects:
- kind: ServiceAccount
  name: knet-stress
  namespace: knet-stress
roleRef:
  kind: Role
  name: knet-stress
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knet-stress
  namespace: knet-stress
  labels:
    app: knet-stress
spec:
  selector:
    matchLabels:
      app: knet-stress
  template:
    metadata:
      labels:
        app: knet-stress
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "6443"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - --connection-rate=2s
        - --endpoint-name=knet-stress
        - --endpoint-namespace=knet-stress
        - --instance-id=$POD_NAME
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: gcr.io/jetstack-josh/knet-stress
        imagePullPolicy: Always
        name: knet-stress
        ports:
        - containerPort: 6433
          protocol: TCP
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: knet-stress
